CREATE TABLE bloggers(
    ID VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL_ID VARCHAR(255) NOT NULL UNIQUE,
    GENDER VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    REGISTERED_AT DATE NOT NULL,
    PRIMARY KEY(ID)
)