CREATE TABLE blogs(
    ID VARCHAR(30) NOT NULL,
    CREATED_BY_USER VARCHAR(30) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(4093) NOT NULL,
    URL_ATTACHMENT VARCHAR(255) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (CREATED_BY_USER) REFERENCES bloggers(ID)
)