CREATE TABLE blogs_map_categories(
	ID VARCHAR(30) NOT NULL,
    BLOG_ID VARCHAR(30) NOT NULL,
    CATEGORY_ID VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (BLOG_ID) REFERENCES blogs(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES categories(ID)
)